on: [push, pull_request]

name: Stable

permissions:
  contents: read
  pull-requests: write

env:
  DEFAULT_OPTIONS: "--features=async,ffi,qlog"
  NO_BORING_OPTIONS: "--features=ffi,qlog --workspace --exclude h3i --exclude tokio-quiche"
  RUSTFLAGS: "-D warnings"
  RUSTTOOLCHAIN: "stable"

concurrency:
  group: ${{ github.ref }}-stable
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  quiche_multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [
          ["aarch64-unknown-linux-gnu", "arm64", "aarch64"],
          # ["i686-unknown-linux-gnu", "i386", "i686"],
        ]
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTTOOLCHAIN }}
          targets: ${{ matrix.targets[0] }}

      - name: Debian cross setup ${{ matrix.targets[1] }}
        run: |
          QEMU_PACKAGES=""
          if [[ "${{ matrix.targets[1] }}" != "i386" ]]; then
            QEMU_PACKAGES="qemu-user libc6:${{ matrix.targets[1] }}"

            sudo dpkg --add-architecture ${{ matrix.targets[1] }}
            # In Ubuntu only ports have packages for other architectures
            THE_ANIMAL_DJ=$(lsb_release -sc)
            echo "
            deb [arch=${{ matrix.targets[1] }}] http://ports.ubuntu.com/ubuntu-ports/ ${THE_ANIMAL_DJ} main restricted universe multiverse
            deb [arch=${{ matrix.targets[1] }}] http://ports.ubuntu.com/ubuntu-ports/ ${THE_ANIMAL_DJ}-updates main restricted universe multiverse
            deb [arch=${{ matrix.targets[1] }}] http://ports.ubuntu.com/ubuntu-ports/ ${THE_ANIMAL_DJ}-security main restricted universe multiverse
            " | sudo tee /etc/apt/sources.list.d/cross-${{ matrix.targets[1] }}.list
            sudo apt-get update || true

            echo >> $GITHUB_ENV CARGO_TARGET_$(echo ${{ matrix.targets[0] }} | tr '[:lower:]-' '[:upper:]_')_RUNNER=qemu-${{ matrix.targets[2] }}
          fi

          sudo apt-get -y --no-install-recommends install crossbuild-essential-${{ matrix.targets[1] }} libclang-dev $QEMU_PACKAGES

          # Configure cmake
          echo >> $GITHUB_ENV CC=/usr/bin/${{ matrix.targets[2] }}-linux-gnu-gcc
          echo >> $GITHUB_ENV CXX=/usr/bin/${{ matrix.targets[2] }}-linux-gnu-g++
          echo >> $GITHUB_ENV CARGO_TARGET_$(echo ${{ matrix.targets[0] }} | tr '[:lower:]-' '[:upper:]_')_LINKER=/usr/bin/${{ matrix.targets[2] }}-linux-gnu-gcc

      - name: Run cargo test ${{ matrix.targets[1] }}
        run: cargo test --target=${{ matrix.targets[0] }} --verbose --all-targets ${{ env.NO_BORING_OPTIONS }}

